# Generated by Django 5.0.6 on 2025-01-02 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_likes_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'session_id')},
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comment'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='news',
        ),
    ]
