# Generated by Django 5.0.6 on 2024-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic_url',
            field=models.URLField(blank=True),
        ),
    ]
