# Generated by Django 5.0.6 on 2024-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='cover_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo_url',
            field=models.URLField(blank=True),
        ),
    ]
