# Generated by Django 5.0.6 on 2024-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cover_photo_profile_cover_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
