# Generated by Django 5.0.6 on 2025-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_club_remove_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Coach'), (3, 'Player'), (4, 'Guest')], default=4),
        ),
    ]
