# Generated by Django 5.0.6 on 2025-01-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_likes_remove_category_blog_blog_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_time',
        ),
    ]
