# Generated by Django 5.0.6 on 2025-01-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelTable(
            name='coach',
            table='coaches',
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
