name: Django backened

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} echo "SSH connection successful"

    - name: Copy backend files to server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "~/"
        port: 22
        timeout: 30s
        command_timeout: 10m
        use_insecure_cipher: false
        rm: false
        debug: true
        strip_components: 0
        overwrite: true

    - name: Migrate and Collect Static Files
      run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
        cd ~/ShotokanUnited_backe &&
        source ../venv/bin/activate &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput

    - name: Restart Gunicorn and Nginx
      run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}
        /bin/systemctl restart gunicorn &&
        /bin/systemctl restart nginx
